"""empty message

Revision ID: 81231b3af11e
Revises: 721de78ea389
Create Date: 2021-05-16 06:53:22.619666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81231b3af11e'
down_revision = '721de78ea389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
