"""empty message

Revision ID: c4ccb41b17d1
Revises: 81231b3af11e
Create Date: 2021-05-16 07:58:54.730270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ccb41b17d1'
down_revision = '81231b3af11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('v_name', sa.String(), nullable=False))
    op.drop_column('Venue', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'v_name')
    # ### end Alembic commands ###
