"""empty message

Revision ID: 8f7e62258d22
Revises: 7f1f186f9bde
Create Date: 2021-05-15 15:23:36.105555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7e62258d22'
down_revision = '7f1f186f9bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seek_venue', sa.String(length=10), nullable=True))
    op.drop_column('Artist', 'seek_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seek_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'seek_venue')
    # ### end Alembic commands ###
